version: '3.8'

services:
  notion-mcp-server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: notion-mcp-server
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    volumes:
      # 필요한 경우 로컬 설정 파일이나 데이터를 볼륨으로 마운트할 수 있습니다
      # - ./config:/app/config
    networks:
      - notion-network

networks:
  notion-network:
    driver: bridge
